  
services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 
    ports:
      - "8088:8000"
      - "9443:9443"

volumes:
  portainer_data:  